[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
env_logger = "0.10.1"
ilog = "1.0.1"
log = "0.4.20"
ureq = "2.9.1"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
